### ISSUE TITLE
Bot no longer sending messages

### ISSUE THREAD

**Issue by elsillygato** [elsillygato/pupperbot-source#2]
^^

**Comment by jllewis11** [comment]
Do you have any of the logs for the error occurring?

**Comment by elsillygato** [comment]
> Do you have any of the logs for the error occurring?

No. :(

**Comment by jllewis11** [comment]
I saw this while researching around https://support-dev.discord.com/hc/en-us/articles/360056426994-Gateway-Update-FAQ


-    You no longer have access to disabled privileged intents if you are not specifying intents
-    You can no longer request member info for multiple guilds at the same time
